---
services:
  reverseproxy:
    image: reverseproxy
    container_name: reverseproxy
    ports:
      - "80:80"
    networks:
      - mynetwork
  
  wordpress:
    image: wordpress_site
    container_name: wordpress
    networks:
      - mynetwork
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    depends_on:
      - mariadb

  mariadb:
    image: database
    container_name: mariadb
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
networks:
  mynetwork:
    external: true