FROM wordpress:latest
COPY ports.conf /etc/apache2/ports.conf
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf
EXPOSE 8080

#RUN sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf
# RUN sed -i 's/<VirtualHost *:80>/<VirtualHost *:8080>/' /etc/apache2/sites-available/000-default.conf